# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MyWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 256, 192))
        self.listWidget.setObjectName("listWidget")

        self.ButtonExit = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonExit.setGeometry(QtCore.QRect(290, 470, 93, 28))
        self.ButtonExit.setObjectName("ButtonExit")

        self.ButtonConnect = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonConnect.setGeometry(QtCore.QRect(290, 500, 93, 28))
        self.ButtonConnect.setObjectName("ButtonConnect")

        self.ButtonFetch = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonFetch.setGeometry(QtCore.QRect(290, 300, 93, 28))
        self.ButtonFetch.setObjectName("ButtonFetch")

        self.ButtonInsert = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonInsert.setGeometry(QtCore.QRect(290, 100, 93, 28))
        self.ButtonInsert.setObjectName("ButtonInsert")

        MainWindow.setCentralWidget(self.centralwidget)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ButtonExit.setText(_translate("MainWindow", "Exit"))
        self.ButtonConnect.setText(_translate("MainWindow", "Connect to DB"))
        self.ButtonFetch.setText(_translate("MainWindow", "Fetch"))
        self.ButtonInsert.setText(_translate("MainWindow", "Insert"))
